name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - run: python3 -m pip install --upgrade build && python3 -m build
      - run: python -m twine upload --repository testpypi --username tamasSL --password myTestPassword999 dist/*