name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: python3 -m pip install --upgrade build &&  pip install -r requirements.txt && python3 -m build
      - run: python -m twine upload --repository ${{ secrets.REPOSITORY_URL }} --username ${{ secrets.REPOSITORY_USER }} --password ${{ secrets.REPOSITORY_PASSWORD }} dist/*